### ISSUE TITLE
Possible conflict with POI Libraries

### ISSUE THREAD

**Issue by PhineasClick** [haiwan/Exporter#20]
Export throws an Exception in exportAsExcel : 

java.lang.NoSuchMethodError: org.apache.poi.ss.usermodel.Font.setBoldweight(S)V
	at org.vaadin.haijian.ExcelFileBuilder.getBoldStyle(ExcelFileBuilder.java:82)
	at org.vaadin.haijian.ExcelFileBuilder.buildColumnHeaderCell(ExcelFileBuilder.java:76)

mabe due to the fact that there is another depebdency POI ( 3.17 )  on my Classpath.

**Comment by haiwan** [comment]
yeah, most likely, POI changed some of the APIs.
